# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [2]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [3]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [4]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [5]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x21a66115fa0
byteorder:  little
byteswap:  False
type: int32


In [6]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [9]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.13512512 0.10884487 0.97542767]
 [0.30335595 0.97495182 0.7038658 ]
 [0.31461008 0.27803741 0.85782165]]


In [10]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [11]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.13512512 0.10884487 0.97542767]
 [0.30335595 0.97495182 0.7038658 ]
 [0.31461008 0.27803741 0.85782165]]
...
float64
(3, 3)
3
2
9
8
72


In [12]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [13]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 

arr1_1 = np.random.rand(3, 4)
print(arr1_1)
print("Тип:", arr1_1.dtype)
print("Розмірність:", arr1_1.shape)
print("Довжина:", len(arr1_1))
print("К-сть вимірів:", arr1_1.ndim)
print("К-сть елементів:", arr1_1.size)
print("Байтів:", arr1_1.itemsize)
print("Память:", arr1_1.nbytes)


[[0.56177556 0.69236225 0.35524291 0.38285929]
 [0.69132039 0.96293963 0.67447591 0.4130902 ]
 [0.14903897 0.52645912 0.91570939 0.79949714]]
Тип: float64
Розмірність: (3, 4)
Довжина: 3
К-сть вимірів: 2
К-сть елементів: 12
Байтів: 8
Память: 96


In [14]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів

arr1_2 = np.array(['a', 'b', 'c', 'd', 'e'])
print(arr1_2)


['a' 'b' 'c' 'd' 'e']


In [15]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою

arr1_3 = np.random.rand(3, 4)
print(arr1_3)


[[0.54599708 0.28056716 0.81402508 0.87809059]
 [0.35926731 0.2470354  0.92971687 0.04177712]
 [0.36618559 0.94307698 0.51819747 0.31449418]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [16]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [18]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [19]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [20]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'

arr2_1 = np.full((3,1,3), False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [21]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int

arr2_2 = arr2_1.reshape(3,3)
arr2_2 = arr2_2.astype("int64")
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21

arr2_3 = np.arange(10,21,2).reshape(2,3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [23]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [24]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[40 36 47 16]
 [27 43 47 33]
 [47 14 20 42]
 [45 24 42 19]]


In [26]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

33


In [27]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[45 24 42 19]


In [28]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[40 36 47 16]
 [27 43 47 33]]


In [29]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[36 47]
 [43 47]
 [14 20]
 [24 42]]


In [30]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[40 36 47 16]
 [47 14 20 42]]


In [31]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[40 36 47 27 43 47 33 47 42 45 24 42]


### ЗАВДАННЯ 3

In [32]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]

arr3_1 = np.random.randint(10, 100, (4, 5))
print(arr3_1)

[[77 65 71 14 42]
 [59 14 40 43 34]
 [20 23 15 89 97]
 [38 39 70 74 79]]


In [33]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку

el3_2 = arr[1, 2]
print(el3_2)

47


In [34]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`

vect3_3 = arr3_1[1]
print(vect3_3)

[59 14 40 43 34]


In [35]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`

vect3_4 = arr3_1[0:4, 2:3]
print(vect3_4)

[[71]
 [40]
 [15]
 [70]]


In [36]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`

mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[14 40]
 [23 15]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [37]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [39]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.90783633 0.36220479 0.32480467 0.69792575 0.7503941 ]
 [0.72426115 0.53385055 0.43996226 0.36725256 0.77053692]
 [0.1856299  0.05604451 0.07981978 0.94034165 0.01247632]
 [0.35960012 0.70701075 0.10365167 0.10129561 0.10636538]
 [0.28519699 0.89604243 0.98135621 0.78461034 0.73271692]]
...
[0.90783633 0.53385055 0.07981978 0.10129561 0.73271692]


In [40]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.90783633 0.72426115 0.1856299  0.35960012 0.28519699]
 [0.36220479 0.53385055 0.05604451 0.70701075 0.89604243]
 [0.32480467 0.43996226 0.07981978 0.10365167 0.98135621]
 [0.69792575 0.36725256 0.94034165 0.10129561 0.78461034]
 [0.7503941  0.77053692 0.01247632 0.10636538 0.73271692]]


In [41]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.01384556842374225


In [42]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 16.6123281  -20.09234277  -7.99960632   2.33496431   3.91357863]
 [ -7.86654785   9.40239683   3.755274     0.55058695  -1.97524883]
 [ 20.65903489 -26.69210958 -10.80617711   1.75710727   6.84133793]
 [ -4.29998219   5.3217911    3.20926162  -0.59920025  -1.16042207]
 [-19.91094601  26.37343815   9.55794495  -3.29388256  -5.66322996]]


### ЗАВАДАННЯ 4

In [43]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200

mat4_1 = np.random.randint(100, 200, (6, 6))
print(mat4_1)

[[109 115 104 143 147 176]
 [189 127 148 174 173 187]
 [177 182 179 129 122 134]
 [146 106 104 109 101 123]
 [101 147 119 164 123 135]
 [179 124 136 182 144 121]]


In [44]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`

diag4_2 = np.diag(mat4_1)
print(diag4_2)

[109 127 179 109 123 121]


In [45]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'

trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[109 189 177 146 101 179]
 [115 127 182 106 147 124]
 [104 148 179 104 119 136]
 [143 174 129 109 164 182]
 [147 173 122 101 123 144]
 [176 187 134 123 135 121]]


In [46]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 

inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 0.00912944 -0.01978197 -0.00222919  0.02282725 -0.01440323  0.01262681]
 [ 0.05634411 -0.07403047  0.01175599  0.01838964 -0.02990101  0.03410367]
 [-0.0701518   0.08939081  0.00209824 -0.03700551  0.04123833 -0.04682666]
 [-0.04574616  0.03728216 -0.01839192  0.00488956  0.03922265 -0.01944128]
 [ 0.09743645 -0.08152435  0.02579395 -0.02851085 -0.07219342  0.06522972]
 [-0.03954745  0.04560129 -0.01414113  0.01555388  0.03251918 -0.04111896]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [48]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [49]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)


In [50]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [51]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [52]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [53]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [54]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [55]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [56]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\vlado\AppData\Local\Temp\ipykernel_8824\3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [57]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [58]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [59]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [60]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [61]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [62]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[2 8 6 9 5]
[2 8 6 9 5]
2312818286416 2312818286416
[2 8 6 9 5]
2312818286416 2312422115728


In [63]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [64]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4

mat5_1 = np.random.randint(1, 20, (4,3))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[ 6 13  2]
 [13 12 15]
 [ 3  5 15]
 [ 4  3  2]]
[21 40 23  9]


In [65]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`

min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

9


In [66]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100

mat5_3 = mat5_1 + 100
print(mat5_3)

[[106 113 102]
 [113 112 115]
 [103 105 115]
 [104 103 102]]


In [67]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`


diag = np.diagonal(mat5_3).reshape(3, 1)
mat5_4 = np.dot(mat5_1, diag)
print(mat5_4)


[[2322]
 [4447]
 [2603]
 [ 990]]


In [68]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці

mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print(np.linalg.matrix_rank(mat5_5))

[[ 106  113  102 2322]
 [ 113  112  115 4447]
 [ 103  105  115 2603]
 [ 104  103  102  990]]
4
